packages:
  - 'frontend'
  - 'cms'
  - 'shared'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@lexical/rich-text'
  - '@lexical/selection'
  - '@lexical/utils'
  - '@lexical/react'
  - '@lexical/html'
  - '@lexical/code'
  - '@lexical/list'
  - '@lexical/table'
  - '@lexical/link'
  - '@lexical/overflow'
  - '@lexical/plain-text'
  - '@lexical/heading'
  - '@lexical/quote'
  - '@lexical/paragraph'
  - '@lexical/root'
  - '@lexical/text'
  - '@lexical/transform'
  - '@lexical/state'
  - '@lexical/theme'
  - '@lexical/editor'
  - '@lexical/events'
  - '@lexical/hashtag'
  - '@lexical/history'
  - '@lexical/keyboard'
  - '@lexical/lexical'
  - '@lexical/mark'
  - '@lexical/markdown'
  - '@lexical/selection'
  - '@lexical/split'
  - '@lexical/string'
  - '@lexical/table'
  - '@lexical/thread'
  - '@lexical/undo'
  - '@lexical/url'
  - '@lexical/utils'
  - '@lexical/websocket'
  - '@lexical/yaml'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp
  - vue-demi
  - workerd
