packages:
  - frontend
  - cms
  - shared

catalogs:
  default:
    '@antfu/eslint-config': ^6.0.0
    '@dnd-kit/core': ^6.3.0
    '@eslint/eslintrc': ^3.1.0
    '@typescript-eslint/parser': ^8.0.0
    'vue-eslint-parser': ^9.4.3
    'eslint-plugin-yml': ^1.18.0
    'yaml-eslint-parser': ^1.3.0
    '@next/eslint-plugin-next': ^15.5.7
    '@iconify-json/lucide': ^1.2.70
    '@iconify-json/radix-icons': ^1.2.5
    '@iconify-json/ri': ^1.2.6
    '@iconify-json/uil': ^1.2.3
    '@inspira-ui/plugins': ^0.0.1
    '@nuxt/fonts': ^0.12.1
    '@nuxt/icon': ^2.0.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/i18n': ^10.1.1
    '@nuxtjs/sitemap': ^7.4.7
    '@payloadcms/db-postgres': 3.69.0
    '@payloadcms/next': 3.69.0
    '@payloadcms/payload-cloud': 3.69.0
    '@payloadcms/richtext-lexical': 3.69.0
    '@payloadcms/storage-vercel-blob': ^3.69.0
    '@payloadcms/ui': 3.69.0
    '@pinia/nuxt': ^0.11.2
    '@playwright/test': 1.57.0
    '@radix-ui/colors': ^3.0.0
    '@splinetool/runtime': ^1.10.82
    '@testing-library/react': 16.3.1
    '@theme-toggles/react': ^4.1.0
    '@tresjs/cientos': ^5.1.0
    '@tresjs/core': ^5.1.0
    '@tresjs/nuxt': ^5.1.0
    '@tresjs/post-processing': ^3.1.0
    '@types/node': ^25.0.3
    '@types/react': ^19.2.7
    '@types/react-dom': 19.2.3
    '@types/three': ^0.178.1
    '@unocss/eslint-plugin': 66.3.3
    '@unocss/nuxt': 66.3.3
    '@unocss/preset-mini': 66.3.3
    '@unocss/reset': 66.3.3
    '@vercel/blob': ^2.0.0
    '@vitejs/plugin-react': 5.1.2
    '@vueuse/core': ^13.9.0
    '@vueuse/integrations': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    '@vueuse/router': ^13.9.0
    animated-unocss: ^0.0.6
    baseline-browser-mapping: ^2.8.31
    clsx: ^2.1.1
    concurrently: ^9.2.1
    consola: ^3.4.2
    cross-env: ^10.1.0
    dotenv: 17.2.3
    eslint: ^9.39.2
    eslint-config-next: 16.1.1
    eslint-plugin-format: ^1.0.2
    focus-trap: ^7.6.5
    graphql: ^16.12.0
    jsdom: 27.4.0
    monaco-editor: ^0.55.1
    motion-v: ^1.7.4
    next: 16.1.1
    nuxt: ^4.1.3
    payload: 3.69.0
    pinia: ^3.0.3
    playwright: 1.57.0
    playwright-core: 1.57.0
    prettier: ^3.7.4
    qs: ^6.14.0
    radix-vue: ^1.9.17
    react: 19.2.3
    react-dom: 19.2.3
    rehype-stringify: ^10.0.1
    reka-ui: ^2.5.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    sass-embedded: ^1.93.2
    sharp: 0.34.5
    simplex-noise: ^4.0.3
    tailwind-merge: ^3.3.1
    theme-colors: ^0.1.0
    three: ^0.178.0
    turbo: ^2.5.8
    typescript: ^5.9.3
    unified: ^11.0.5
    unocss: 66.3.3
    unocss-preset-animations: 1.1.1
    unocss-preset-radix: 2.8.0
    vite-tsconfig-paths: 6.0.3
    vitest: 4.0.16
    vue: ^3.5.22
    vue-i18n: ^11.1.12
    vue-router: ^4.6.3
    wrangler: ^4.43.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@lexical/rich-text'
  - '@lexical/selection'
  - '@lexical/utils'
  - '@lexical/react'
  - '@lexical/html'
  - '@lexical/code'
  - '@lexical/list'
  - '@lexical/table'
  - '@lexical/link'
  - '@lexical/overflow'
  - '@lexical/plain-text'
  - '@lexical/heading'
  - '@lexical/quote'
  - '@lexical/paragraph'
  - '@lexical/root'
  - '@lexical/text'
  - '@lexical/transform'
  - '@lexical/state'
  - '@lexical/theme'
  - '@lexical/editor'
  - '@lexical/events'
  - '@lexical/hashtag'
  - '@lexical/history'
  - '@lexical/keyboard'
  - '@lexical/lexical'
  - '@lexical/mark'
  - '@lexical/markdown'
  - '@lexical/selection'
  - '@lexical/split'
  - '@lexical/string'
  - '@lexical/table'
  - '@lexical/thread'
  - '@lexical/undo'
  - '@lexical/url'
  - '@lexical/utils'
  - '@lexical/websocket'
  - '@lexical/yaml'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp
  - vue-demi
  - workerd
