packages:
  - frontend
  - cms
  - shared

catalogs:
  frontend:
    '@nuxt/devtools-kit': 3.1.1
    '@dimforge/rapier3d-compat': ^0.19.3
    '@iconify-json/lucide': ^1.2.87
    '@iconify-json/radix-icons': ^1.2.6
    '@iconify-json/ri': ^1.2.8
    '@iconify-json/uil': ^1.2.3
    '@nuxt/icon': ^2.2.1
    '@nuxt/image': ^2.0.0
    '@nuxtjs/color-mode': ^4.0.0
    '@nuxtjs/i18n': ^10.2.1
    '@nuxtjs/sitemap': ^7.6.0
    '@pinia/nuxt': ^0.11.3
    '@radix-ui/colors': ^3.0.0
    '@splinetool/runtime': ^1.12.46
    '@theme-toggles/react': ^4.1.0
    '@tresjs/cientos': ^5.2.5
    '@tresjs/core': ^5.3.3
    '@tresjs/nuxt': ^5.1.7
    '@tresjs/post-processing': ^3.2.5
    '@unocss/reset': 66.3.3
    '@vueuse/core': ^14.1.0
    '@vueuse/integrations': ^14.1.0
    '@vueuse/nuxt': ^14.1.0
    '@vueuse/router': ^14.1.0
    clsx: ^2.1.1
    consola: ^3.4.2
    fast-xml-parser: ^5.3.4
    focus-trap: ^8.0.0
    gsap: ^3.14.2
    lenis: ^1.3.17
    motion-v: ^1.10.2
    nuxt: ^4.3.0
    pinia: ^3.0.4
    qs: ^6.14.1
    radix-vue: ^1.9.17
    rehype-stringify: ^10.0.1
    reka-ui: ^2.8.0
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    simplex-noise: ^4.0.3
    tailwind-merge: ^3.4.0
    theme-colors: ^0.1.0
    three: ^0.182.0
    unified: ^11.0.5
    vue: ^3.5.27
    vue-i18n: ^11.2.8
    vue-router: ^5.0.1
  cms:
    bufferutil: ^4.0.9
    '@dnd-kit/core': ^6.3.1
    '@payloadcms/db-postgres': 3.73.0
    '@payloadcms/next': 3.73.0
    '@payloadcms/payload-cloud': 3.73.0
    '@payloadcms/richtext-lexical': 3.73.0
    '@payloadcms/storage-vercel-blob': 3.73.0
    '@payloadcms/ui': 3.73.0
    '@vercel/blob': ^2.0.1
    cross-env: ^10.1.0
    dotenv: 17.2.3
    graphql: ^16.12.0
    next: 16.1.6
    payload: 3.73.0
    react: 19.2.3
    react-dom: 19.2.3
    utf-8-validate: ^6.0.5
  common:
    monaco-editor: ^0.55.1
    sharp: 0.34.5
  build:
    '@inspira-ui/plugins': ^0.0.1
    '@nuxt/fonts': ^0.13.0
    '@vitejs/plugin-vue': ^6.0.4
    next-rspack: 16.1.1
    rolldown: 1.0.0-beta.53
    rolldown-vite: 7.3.1
    '@rspack/core': ^1.7.4
    '@unocss/nuxt': 66.3.3
    '@unocss/preset-mini': 66.3.3
    '@vitejs/plugin-react': 5.1.2
    animated-unocss: ^0.0.6
    baseline-browser-mapping: ^2.9.19
    sass-embedded: ^1.97.3
    unocss: 66.3.3
    unocss-preset-animations: 1.1.1
    unocss-preset-radix: 2.8.0
    vite-tsconfig-paths: 6.0.3
    wrangler: ^4.61.1
  dev:
    '@storybook/addon-docs': 10.2.8
    '@storybook/vue3-vite': 10.2.8
    storybook: 10.2.8
    '@antfu/eslint-config': ^7.2.0
    '@eslint/eslintrc': ^3.3.3
    '@next/eslint-plugin-next': ^16.1.6
    '@playwright/test': 1.57.0
    '@testing-library/react': 16.3.1
    '@typescript-eslint/parser': ^8.54.0
    '@unocss/eslint-plugin': 66.3.3
    concurrently: ^9.2.1
    eslint: ^9.39.2
    eslint-config-next: 16.1.1
    eslint-plugin-format: ^1.3.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-yml: ^3.0.0
    jsdom: 27.4.0
    playwright: 1.57.0
    playwright-core: 1.57.0
    prettier: ^3.8.1
    taze: ^19.9.2
    turbo: ^2.8.1
    typescript: ^5.9.3
    vitest: 4.0.16
    vue-eslint-parser: ^10.2.0
    vue-tsc: ^3.2.4
    yaml-eslint-parser: ^2.0.0
  types:
    '@types/node': ^25.1.0
    '@types/react': ^19.2.10
    '@types/react-dom': 19.2.3
    '@types/three': ^0.182.0

onlyBuiltDependencies:
  - bufferutil
  - '@parcel/watcher'
  - '@swc/core'
  - '@lexical/rich-text'
  - '@lexical/selection'
  - '@lexical/utils'
  - '@lexical/react'
  - '@lexical/html'
  - '@lexical/code'
  - '@lexical/list'
  - '@lexical/table'
  - '@lexical/link'
  - '@lexical/overflow'
  - '@lexical/plain-text'
  - '@lexical/heading'
  - '@lexical/quote'
  - '@lexical/paragraph'
  - '@lexical/root'
  - '@lexical/text'
  - '@lexical/transform'
  - '@lexical/state'
  - '@lexical/theme'
  - '@lexical/editor'
  - '@lexical/events'
  - '@lexical/hashtag'
  - '@lexical/history'
  - '@lexical/keyboard'
  - '@lexical/lexical'
  - '@lexical/mark'
  - '@lexical/markdown'
  - '@lexical/selection'
  - '@lexical/split'
  - '@lexical/string'
  - '@lexical/table'
  - '@lexical/thread'
  - '@lexical/undo'
  - '@lexical/url'
  - '@lexical/utils'
  - '@lexical/websocket'
  - '@lexical/yaml'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp
  - utf-8-validate
  - vue-demi
  - workerd
catalog:
  vite: 7.3.1
