import type { UserShortcuts } from 'unocss'

export const typographyShortcuts: UserShortcuts = [
  ['ui-type-size-xs', 'text-[length:var(--type-size-xs)] leading-[var(--type-leading-xs)]'],
  ['ui-type-size-sm', 'text-[length:var(--type-size-sm)] leading-[var(--type-leading-sm)]'],
  ['ui-type-size-md', 'text-[length:var(--type-size-md)] leading-[var(--type-leading-md)]'],
  ['ui-type-size-lg', 'text-[length:var(--type-size-lg)] leading-[var(--type-leading-lg)]'],
  ['ui-type-size-xl', 'text-[length:var(--type-size-xl)] leading-[var(--type-leading-xl)]'],
  ['ui-type-size-2xl', 'text-[length:var(--type-size-2xl)] leading-[var(--type-leading-2xl)]'],
  ['ui-type-size-3xl', 'text-[length:var(--type-size-3xl)] leading-[var(--type-leading-3xl)]'],
  ['ui-type-size-4xl', 'text-[length:var(--type-size-4xl)] leading-[var(--type-leading-4xl)]'],

  ['ui-type-display-xs', '[font-family:var(--type-family-display-compact)] [font-synthesis:none] ui-type-size-xs tracking-[var(--type-track-display-xs)] md:tracking-[var(--type-track-display-xs-md)]'],
  ['ui-type-display-sm', '[font-family:var(--type-family-display-compact)] [font-synthesis:none] ui-type-size-sm tracking-[var(--type-track-display-sm)] md:tracking-[var(--type-track-display-sm-md)]'],
  ['ui-type-display-md', '[font-family:var(--type-family-display-hero)] [font-synthesis:none] ui-type-size-md tracking-[var(--type-track-display-md)] md:tracking-[var(--type-track-display-md-md)]'],
  ['ui-type-display-lg', '[font-family:var(--type-family-display-hero)] [font-synthesis:none] ui-type-size-lg tracking-[var(--type-track-display-lg)] md:tracking-[var(--type-track-display-lg-md)]'],
  ['ui-type-display-xl', '[font-family:var(--type-family-display-hero)] [font-synthesis:none] ui-type-size-xl tracking-[var(--type-track-display-xl)] md:tracking-[var(--type-track-display-xl-md)]'],
  ['ui-type-display-2xl', '[font-family:var(--type-family-display-hero)] [font-synthesis:none] ui-type-size-2xl tracking-[var(--type-track-display-2xl)] md:tracking-[var(--type-track-display-2xl-md)]'],
  ['ui-type-display-3xl', '[font-family:var(--type-family-display-hero)] [font-synthesis:none] ui-type-size-3xl tracking-[var(--type-track-display-3xl)] md:tracking-[var(--type-track-display-3xl-md)]'],
  ['ui-type-display-4xl', '[font-family:var(--type-family-display-hero)] [font-synthesis:none] ui-type-size-4xl tracking-[var(--type-track-display-4xl)] md:tracking-[var(--type-track-display-4xl-md)]'],

  ['ui-type-headline-xs', '[font-family:var(--type-family-headline)] ui-type-size-xs'],
  ['ui-type-headline-sm', '[font-family:var(--type-family-headline)] ui-type-size-sm'],
  ['ui-type-headline-md', '[font-family:var(--type-family-headline)] ui-type-size-md'],
  ['ui-type-headline-lg', '[font-family:var(--type-family-headline)] ui-type-size-lg'],
  ['ui-type-headline-xl', '[font-family:var(--type-family-headline)] ui-type-size-xl'],
  ['ui-type-headline-2xl', '[font-family:var(--type-family-headline)] ui-type-size-2xl'],
  ['ui-type-headline-3xl', '[font-family:var(--type-family-headline)] ui-type-size-3xl'],
  ['ui-type-headline-4xl', '[font-family:var(--type-family-headline)] ui-type-size-4xl'],

  ['ui-type-body-xs', '[font-family:var(--type-family-body)] ui-type-size-xs'],
  ['ui-type-body-sm', '[font-family:var(--type-family-body)] ui-type-size-sm'],
  ['ui-type-body-md', '[font-family:var(--type-family-body)] ui-type-size-md'],
  ['ui-type-body-lg', '[font-family:var(--type-family-body)] ui-type-size-lg'],
  ['ui-type-body-xl', '[font-family:var(--type-family-body)] ui-type-size-xl'],
  ['ui-type-body-2xl', '[font-family:var(--type-family-body)] ui-type-size-2xl'],
  ['ui-type-body-3xl', '[font-family:var(--type-family-body)] ui-type-size-3xl'],
  ['ui-type-body-4xl', '[font-family:var(--type-family-body)] ui-type-size-4xl'],

  ['ui-type-meta-xs', '[font-family:var(--type-family-meta)] ui-type-size-xs tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-sm', '[font-family:var(--type-family-meta)] ui-type-size-sm tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-md', '[font-family:var(--type-family-meta)] ui-type-size-md tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-lg', '[font-family:var(--type-family-meta)] ui-type-size-lg tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-xl', '[font-family:var(--type-family-meta)] ui-type-size-xl tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-2xl', '[font-family:var(--type-family-meta)] ui-type-size-2xl tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-3xl', '[font-family:var(--type-family-meta)] ui-type-size-3xl tracking-[var(--type-track-meta)]'],
  ['ui-type-meta-4xl', '[font-family:var(--type-family-meta)] ui-type-size-4xl tracking-[var(--type-track-meta)]'],

  ['ui-type-quote-xs', '[font-family:var(--type-family-quote)] italic ui-type-size-xs'],
  ['ui-type-quote-sm', '[font-family:var(--type-family-quote)] italic ui-type-size-sm'],
  ['ui-type-quote-md', '[font-family:var(--type-family-quote)] italic ui-type-size-md'],
  ['ui-type-quote-lg', '[font-family:var(--type-family-quote)] italic ui-type-size-lg'],
  ['ui-type-quote-xl', '[font-family:var(--type-family-quote)] italic ui-type-size-xl'],
  ['ui-type-quote-2xl', '[font-family:var(--type-family-quote)] italic ui-type-size-2xl'],
  ['ui-type-quote-3xl', '[font-family:var(--type-family-quote)] italic ui-type-size-3xl'],
  ['ui-type-quote-4xl', '[font-family:var(--type-family-quote)] italic ui-type-size-4xl'],

  ['ui-type-signal-xs', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-xs'],
  ['ui-type-signal-sm', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-sm'],
  ['ui-type-signal-md', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-md'],
  ['ui-type-signal-lg', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-lg'],
  ['ui-type-signal-xl', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-xl'],
  ['ui-type-signal-2xl', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-2xl'],
  ['ui-type-signal-3xl', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-3xl'],
  ['ui-type-signal-4xl', '[font-family:var(--type-family-signal)] [font-weight:600] ui-type-size-4xl'],
]
