import type { UserShortcuts } from 'unocss'

export const typographyShortcuts: UserShortcuts = [
  ['ui-type-size-xs', 'text-type-size-xs leading-$type-leading-xs'],
  ['ui-type-size-sm', 'text-type-size-sm leading-$type-leading-sm'],
  ['ui-type-size-md', 'text-type-size-md leading-$type-leading-md'],
  ['ui-type-size-lg', 'text-type-size-lg leading-$type-leading-lg'],
  ['ui-type-size-xl', 'text-type-size-xl leading-$type-leading-xl'],
  ['ui-type-size-2xl', 'text-type-size-2xl leading-$type-leading-2xl'],
  ['ui-type-size-3xl', 'text-type-size-3xl leading-$type-leading-3xl'],
  ['ui-type-size-4xl', 'text-type-size-4xl leading-$type-leading-4xl'],

  ['ui-type-display-xs', 'font-type-family-display-compact font-synthesis-none ui-type-size-xs tracking-$type-track-display-xs md:tracking-$type-track-display-xs-md'],
  ['ui-type-display-sm', 'font-type-family-display-compact font-synthesis-none ui-type-size-sm tracking-$type-track-display-sm md:tracking-$type-track-display-sm-md'],
  ['ui-type-display-md', 'font-type-family-display-hero font-synthesis-none ui-type-size-md tracking-$type-track-display-md md:tracking-$type-track-display-md-md'],
  ['ui-type-display-lg', 'font-type-family-display-hero font-synthesis-none ui-type-size-lg tracking-$type-track-display-lg md:tracking-$type-track-display-lg-md'],
  ['ui-type-display-xl', 'font-type-family-display-hero font-synthesis-none ui-type-size-xl tracking-$type-track-display-xl md:tracking-$type-track-display-xl-md'],
  ['ui-type-display-2xl', 'font-type-family-display-hero font-synthesis-none ui-type-size-2xl tracking-$type-track-display-2xl md:tracking-$type-track-display-2xl-md'],
  ['ui-type-display-3xl', 'font-type-family-display-hero font-synthesis-none ui-type-size-3xl tracking-$type-track-display-3xl md:tracking-$type-track-display-3xl-md'],
  ['ui-type-display-4xl', 'font-type-family-display-hero font-synthesis-none ui-type-size-4xl tracking-$type-track-display-4xl md:tracking-$type-track-display-4xl-md'],

  ['ui-type-headline-xs', 'font-type-family-headline ui-type-size-xs'],
  ['ui-type-headline-sm', 'font-type-family-headline ui-type-size-sm'],
  ['ui-type-headline-md', 'font-type-family-headline ui-type-size-md'],
  ['ui-type-headline-lg', 'font-type-family-headline ui-type-size-lg'],
  ['ui-type-headline-xl', 'font-type-family-headline ui-type-size-xl'],
  ['ui-type-headline-2xl', 'font-type-family-headline ui-type-size-2xl'],
  ['ui-type-headline-3xl', 'font-type-family-headline ui-type-size-3xl'],
  ['ui-type-headline-4xl', 'font-type-family-headline ui-type-size-4xl'],

  ['ui-type-body-xs', 'font-type-family-body ui-type-size-xs'],
  ['ui-type-body-sm', 'font-type-family-body ui-type-size-sm'],
  ['ui-type-body-md', 'font-type-family-body ui-type-size-md'],
  ['ui-type-body-lg', 'font-type-family-body ui-type-size-lg'],
  ['ui-type-body-xl', 'font-type-family-body ui-type-size-xl'],
  ['ui-type-body-2xl', 'font-type-family-body ui-type-size-2xl'],
  ['ui-type-body-3xl', 'font-type-family-body ui-type-size-3xl'],
  ['ui-type-body-4xl', 'font-type-family-body ui-type-size-4xl'],

  ['ui-type-meta-xs', 'font-type-family-meta ui-type-size-xs tracking-$type-track-meta'],
  ['ui-type-meta-sm', 'font-type-family-meta ui-type-size-sm tracking-$type-track-meta'],
  ['ui-type-meta-md', 'font-type-family-meta ui-type-size-md tracking-$type-track-meta'],
  ['ui-type-meta-lg', 'font-type-family-meta ui-type-size-lg tracking-$type-track-meta'],
  ['ui-type-meta-xl', 'font-type-family-meta ui-type-size-xl tracking-$type-track-meta'],
  ['ui-type-meta-2xl', 'font-type-family-meta ui-type-size-2xl tracking-$type-track-meta'],
  ['ui-type-meta-3xl', 'font-type-family-meta ui-type-size-3xl tracking-$type-track-meta'],
  ['ui-type-meta-4xl', 'font-type-family-meta ui-type-size-4xl tracking-$type-track-meta'],

  ['ui-type-quote-xs', 'font-type-family-quote italic ui-type-size-xs'],
  ['ui-type-quote-sm', 'font-type-family-quote italic ui-type-size-sm'],
  ['ui-type-quote-md', 'font-type-family-quote italic ui-type-size-md'],
  ['ui-type-quote-lg', 'font-type-family-quote italic ui-type-size-lg'],
  ['ui-type-quote-xl', 'font-type-family-quote italic ui-type-size-xl'],
  ['ui-type-quote-2xl', 'font-type-family-quote italic ui-type-size-2xl'],
  ['ui-type-quote-3xl', 'font-type-family-quote italic ui-type-size-3xl'],
  ['ui-type-quote-4xl', 'font-type-family-quote italic ui-type-size-4xl'],

  ['ui-type-signal-xs', 'font-type-family-signal font-semibold ui-type-size-xs'],
  ['ui-type-signal-sm', 'font-type-family-signal font-semibold ui-type-size-sm'],
  ['ui-type-signal-md', 'font-type-family-signal font-semibold ui-type-size-md'],
  ['ui-type-signal-lg', 'font-type-family-signal font-semibold ui-type-size-lg'],
  ['ui-type-signal-xl', 'font-type-family-signal font-semibold ui-type-size-xl'],
  ['ui-type-signal-2xl', 'font-type-family-signal font-semibold ui-type-size-2xl'],
  ['ui-type-signal-3xl', 'font-type-family-signal font-semibold ui-type-size-3xl'],
  ['ui-type-signal-4xl', 'font-type-family-signal font-semibold ui-type-size-4xl'],
]
