import { PURE_BLACK, PURE_WHITE, radiusTheme, spacingTheme, themeColors, typographyTheme } from './palette'

const animations = {
  keyframes: {
    'enter-from-right': '{0%{opacity:0;transform:translateX(200px);}100%{opacity:1;transform:translateX(0);}}',
    'enter-from-left': '{0%{opacity:0;transform:translateX(-200px);}100%{opacity:1;transform:translateX(0);}}',
    'exit-to-right': '{0%{opacity:1;transform:translateX(0);}100%{opacity:0;transform:translateX(200px);}}',
    'exit-to-left': '{0%{opacity:1;transform:translateX(0);}100%{opacity:0;transform:translateX(-200px);}}',
    'scale-in': '{0%{opacity:0;transform:rotateX(-10deg) scale(0.9);}100%{opacity:1;transform:rotateX(0deg) scale(1);}}',
    'scale-out': '{0%{opacity:1;transform:rotateX(0deg) scale(1);}100%{opacity:0;transform:rotateX(-10deg) scale(0.95);}}',
    'fade-in': '{0%{opacity:0;}100%{opacity:1;}}',
    'fade-out': '{0%{opacity:1;}100%{opacity:0;}}',
    'ui-ghost-underline-sweep': '{0%{transform:scaleX(1) rotate(0.001deg);transform-origin:right;}49%{transform:scaleX(0) rotate(0.001deg);transform-origin:right;}50%{transform:scaleX(0) rotate(0.001deg);transform-origin:left;}100%{transform:scaleX(1) rotate(0.001deg);transform-origin:left;}}',
    'shake-in': '{0%{opacity:0;transform:translateX(-6px);}20%{opacity:1;transform:translateX(4px);}40%{transform:translateX(-3px);}60%{transform:translateX(2px);}80%{transform:translateX(-1px);}100%{opacity:1;transform:translateX(0);}}',
    'ds-badge-shimmer': '{0%{background-position:100% 0;}100%{background-position:-100% 0;}}',
    'ds-badge-beam': '{100%{transform:rotate(360deg);}}',
  },
  durations: {
    'enter-from-right': '250ms',
    'enter-from-left': '250ms',
    'exit-to-right': '250ms',
    'exit-to-left': '250ms',
    'scale-in': '200ms',
    'scale-out': '200ms',
    'fade-in': '200ms',
    'fade-out': '200ms',
    'ui-ghost-underline-sweep': '650ms',
    'shake-in': 'var(--motion-input-error-shake-duration)',
    'ds-badge-shimmer': 'var(--motion-badge-shimmer-duration)',
    'ds-badge-beam': 'var(--motion-badge-beam-duration)',
  },
  timingFns: {
    'enter-from-right': 'ease',
    'enter-from-left': 'ease',
    'exit-to-right': 'ease',
    'exit-to-left': 'ease',
    'scale-in': 'ease',
    'scale-out': 'ease',
    'fade-in': 'ease',
    'fade-out': 'ease',
    'ui-ghost-underline-sweep': 'ease',
    'shake-in': 'var(--motion-input-error-shake-ease)',
    'ds-badge-shimmer': 'var(--motion-badge-shimmer-ease)',
    'ds-badge-beam': 'var(--motion-badge-beam-ease)',
  },
  counts: {
    'enter-from-right': '1',
    'enter-from-left': '1',
    'exit-to-right': '1',
    'exit-to-left': '1',
    'scale-in': '1',
    'scale-out': '1',
    'fade-in': '1',
    'fade-out': '1',
    'ui-ghost-underline-sweep': '1',
    'shake-in': '1',
    'ds-badge-shimmer': 'infinite',
    'ds-badge-beam': 'infinite',
  },
}

export const theme = {
  colors: {
    pureBlack: PURE_BLACK,
    pureWhite: PURE_WHITE,
    ...themeColors,
  },
  fontSize: typographyTheme.fontSize,
  fontFamily: typographyTheme.fontFamily,
  spacing: spacingTheme,
  borderRadius: radiusTheme,
  animation: animations,
  duration: {},
  timingFns: {},
  properties: {},
  counts: {},
}
