import type { SourceConfig } from './types'

export const sources: SourceConfig[] = [
  {
    id: 'heise',
    name: 'heise online',
    type: 'rss',
    url: 'https://heise.de/rss/heise-atom.xml',
    language: 'de',
    topics: ['tech', 'security', 'ai'],
    weight: 1.0,
  },
  {
    id: 'golem-softwareentwicklung',
    name: 'Golem.de – Software-Entwicklung',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=softwareentwicklung',
    language: 'de',
    topics: ['tech', 'software', 'dev'],
    weight: 0.95,
  },
  {
    id: 'golem-software',
    name: 'Golem.de – Software',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=software',
    language: 'de',
    topics: ['tech', 'software'],
    weight: 0.95,
  },
  {
    id: 'golem-opensource',
    name: 'Golem.de – Open Source',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=open-source',
    language: 'de',
    topics: ['tech', 'software', 'opensource'],
    weight: 0.95,
  },
  {
    id: 'golem-internet',
    name: 'Golem.de – Internet',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=internet',
    language: 'de',
    topics: ['tech', 'internet', 'policy'],
    weight: 0.95,
  },
  {
    id: 'golem-wirtschaft',
    name: 'Golem.de – Wirtschaft',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=wirtschaft',
    language: 'de',
    topics: ['tech', 'business'],
    weight: 0.95,
  },
  {
    id: 'golem-wissenschaft',
    name: 'Golem.de – Wissenschaft',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=wissenschaft',
    language: 'de',
    topics: ['tech', 'science'],
    weight: 0.95,
  },
  {
    id: 'golem-security',
    name: 'Golem.de – Security',
    type: 'rss',
    url: 'https://rss.golem.de/rss.php?feed=ATOM1.0&ms=security',
    language: 'de',
    topics: ['tech', 'security'],
    weight: 0.95,
  },
  {
    id: 't3n',
    name: 't3n',
    type: 'rss',
    url: 'https://t3n.de/rss.xml',
    language: 'de',
    topics: ['tech', 'business', 'ai'],
    weight: 0.9,
  },
  {
    id: 'netzpolitik',
    name: 'Netzpolitik.org',
    type: 'rss',
    url: 'https://netzpolitik.org/feed/',
    language: 'de',
    topics: ['policy', 'privacy', 'security'],
    weight: 0.9,
  },
  {
    id: 'computerbase',
    name: 'ComputerBase',
    type: 'rss',
    url: 'https://www.computerbase.de/rss/news.xml',
    language: 'de',
    topics: ['hardware', 'tech', 'reviews'],
    weight: 0.9,
  },
  {
    id: 'arstechnica',
    name: 'Ars Technica',
    type: 'rss',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    language: 'en',
    topics: ['tech', 'science', 'security'],
    weight: 0.95,
  },
  {
    id: 'theverge',
    name: 'The Verge',
    type: 'rss',
    url: 'https://www.theverge.com/rss/index.xml',
    language: 'en',
    topics: ['tech', 'gadgets'],
    weight: 0.9,
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    type: 'rss',
    url: 'https://techcrunch.com/feed/',
    language: 'en',
    topics: ['startups', 'tech', 'venture'],
    weight: 0.9,
  },
  {
    id: 'wired',
    name: 'WIRED',
    type: 'rss',
    url: 'https://www.wired.com/feed/rss',
    language: 'en',
    topics: ['tech', 'science', 'business'],
    weight: 0.9,
  },
  {
    id: 'reuters-tech',
    name: 'Reuters – Technology (RSS.app)',
    type: 'json',
    url: 'https://rss.app/feeds/v1.1/INOw5Gizjy2c2l5k.json',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.85,
  },
  {
    id: 'mittr',
    name: 'MIT Technology Review',
    type: 'rss',
    url: 'https://www.technologyreview.com/feed/',
    language: 'en',
    topics: ['tech', 'ai', 'science'],
    weight: 0.85,
  },
  {
    id: 'theregister',
    name: 'The Register',
    type: 'rss',
    url: 'https://www.theregister.com/headlines.atom',
    language: 'en',
    topics: ['tech', 'security', 'enterprise'],
    weight: 0.85,
  },
]
