import type { SourcePreset } from './types'

export const presets: SourcePreset[] = [
  {
    id: 'reuters-tech',
    name: 'Reuters – Technology',
    googleMode: 'search',
    googleQuery: 'site:reuters.com/technology',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.9,
  },
  {
    id: 'heise',
    name: 'heise online',
    googleMode: 'search',
    googleQuery: 'site:heise.de',
    language: 'de',
    topics: ['tech', 'security', 'ai'],
    weight: 1.0,
  },
  {
    id: 'golem',
    name: 'Golem.de',
    googleMode: 'search',
    googleQuery: 'site:golem.de',
    language: 'de',
    topics: ['tech', 'software', 'dev'],
    weight: 0.95,
  },
  {
    id: 't3n',
    name: 't3n',
    googleMode: 'search',
    googleQuery: 'site:t3n.de',
    language: 'de',
    topics: ['tech', 'business', 'ai'],
    weight: 0.9,
  },
  {
    id: 'netzpolitik',
    name: 'Netzpolitik.org',
    googleMode: 'search',
    googleQuery: 'site:netzpolitik.org',
    language: 'de',
    topics: ['policy', 'privacy', 'security'],
    weight: 0.9,
  },
  {
    id: 'computerbase',
    name: 'ComputerBase',
    googleMode: 'search',
    googleQuery: 'site:computerbase.de',
    language: 'de',
    topics: ['hardware', 'tech', 'reviews'],
    weight: 0.9,
  },
  {
    id: 'arstechnica',
    name: 'Ars Technica',
    googleMode: 'search',
    googleQuery: 'site:arstechnica.com',
    language: 'en',
    topics: ['tech', 'science', 'security'],
    weight: 0.95,
  },
  {
    id: 'theverge',
    name: 'The Verge',
    googleMode: 'search',
    googleQuery: 'site:theverge.com',
    language: 'en',
    topics: ['tech', 'gadgets'],
    weight: 0.9,
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    googleMode: 'search',
    googleQuery: 'site:techcrunch.com',
    language: 'en',
    topics: ['startups', 'tech', 'venture'],
    weight: 0.9,
  },
  {
    id: 'wired',
    name: 'WIRED',
    googleMode: 'search',
    googleQuery: 'site:wired.com',
    language: 'en',
    topics: ['tech', 'science', 'business'],
    weight: 0.9,
  },
  {
    id: 'mittr',
    name: 'MIT Technology Review',
    googleMode: 'search',
    googleQuery: 'site:technologyreview.com',
    language: 'en',
    topics: ['tech', 'ai', 'science'],
    weight: 0.85,
  },
  {
    id: 'theregister',
    name: 'The Register',
    googleMode: 'search',
    googleQuery: 'site:theregister.com',
    language: 'en',
    topics: ['tech', 'security', 'enterprise'],
    weight: 0.85,
  },
]
