import type { SourcePreset } from './types'

export const presets: SourcePreset[] = [
  {
    id: 'golem',
    name: 'Golem.de',
    googleMode: 'search',
    googleQuery: 'site:golem.de',
    language: 'de',
    topics: ['tech', 'software', 'dev'],
    weight: 1.0,
  },
  {
    id: 'heise',
    name: 'heise online',
    googleMode: 'search',
    googleQuery: 'site:heise.de',
    language: 'de',
    topics: ['tech', 'security', 'ai'],
    weight: 0.98,
  },
  {
    id: 't3n',
    name: 't3n',
    googleMode: 'search',
    googleQuery: 'site:t3n.de',
    language: 'de',
    topics: ['tech', 'business', 'ai'],
    weight: 0.96,
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    googleMode: 'search',
    googleQuery: 'site:techcrunch.com',
    language: 'en',
    topics: ['tech', 'software', 'ai'],
    weight: 0.95,
  },
  {
    id: 'arstechnica',
    name: 'Ars Technica',
    googleMode: 'search',
    googleQuery: 'site:arstechnica.com',
    language: 'en',
    topics: ['tech', 'software', 'security'],
    weight: 0.95,
  },
  {
    id: 'theregister',
    name: 'The Register',
    googleMode: 'search',
    googleQuery: 'site:theregister.com',
    language: 'en',
    topics: ['tech', 'security', 'enterprise'],
    weight: 0.94,
  },
  {
    id: 'bleepingcomputer',
    name: 'BleepingComputer',
    googleMode: 'search',
    googleQuery: 'site:bleepingcomputer.com',
    language: 'en',
    topics: ['security', 'tech'],
    weight: 0.93,
  },
  {
    id: 'therecord',
    name: 'The Record',
    googleMode: 'search',
    googleQuery: 'site:therecord.media',
    language: 'en',
    topics: ['security', 'tech'],
    weight: 0.93,
  },
  {
    id: 'mittr',
    name: 'MIT Technology Review',
    googleMode: 'search',
    googleQuery: 'site:technologyreview.com',
    language: 'en',
    topics: ['tech', 'ai', 'science'],
    weight: 0.92,
  },
  {
    id: 'theinformation',
    name: 'The Information',
    googleMode: 'search',
    googleQuery: 'site:theinformation.com',
    language: 'en',
    topics: ['tech', 'software', 'business'],
    weight: 0.91,
  },
  {
    id: 'wired',
    name: 'WIRED',
    googleMode: 'search',
    googleQuery: 'site:wired.com',
    language: 'en',
    topics: ['tech', 'science'],
    weight: 0.9,
  },
  {
    id: '404media',
    name: '404 Media',
    googleMode: 'search',
    googleQuery: 'site:404media.co',
    language: 'en',
    topics: ['tech', 'policy'],
    weight: 0.89,
  },
  {
    id: 'techdirt',
    name: 'Techdirt',
    googleMode: 'search',
    googleQuery: 'site:techdirt.com',
    language: 'en',
    topics: ['tech', 'policy'],
    weight: 0.88,
  },
  {
    id: 'simonwillison',
    name: "Simon Willison's Weblog",
    googleMode: 'search',
    googleQuery: 'site:simonwillison.net',
    language: 'en',
    topics: ['tech', 'software', 'ai'],
    weight: 0.87,
  },
  {
    id: 'nextgov',
    name: 'Nextgov/FCW',
    googleMode: 'search',
    googleQuery: 'site:nextgov.com',
    language: 'en',
    topics: ['tech', 'policy'],
    weight: 0.86,
  },
  {
    id: 'techmeme',
    name: 'Techmeme',
    googleMode: 'search',
    googleQuery: 'site:techmeme.com',
    language: 'en',
    topics: ['tech'],
    weight: 0.85,
  },
  {
    id: 'netzpolitik',
    name: 'Netzpolitik.org',
    googleMode: 'search',
    googleQuery: 'site:netzpolitik.org',
    language: 'de',
    topics: ['policy', 'privacy', 'security'],
    weight: 0.84,
  },
  {
    id: 'theverge',
    name: 'The Verge',
    googleMode: 'search',
    googleQuery: 'site:theverge.com',
    language: 'en',
    topics: ['tech', 'product'],
    weight: 0.83,
  },
  {
    id: '9to5google',
    name: '9to5Google',
    googleMode: 'search',
    googleQuery: 'site:9to5google.com',
    language: 'en',
    topics: ['tech', 'software'],
    weight: 0.82,
  },
  {
    id: '9to5mac',
    name: '9to5Mac',
    googleMode: 'search',
    googleQuery: 'site:9to5mac.com',
    language: 'en',
    topics: ['tech', 'software'],
    weight: 0.82,
  },
  {
    id: 'windowscentral',
    name: 'Windows Central',
    googleMode: 'search',
    googleQuery: 'site:windowscentral.com',
    language: 'en',
    topics: ['tech', 'software'],
    weight: 0.81,
  },
  {
    id: 'androidauthority',
    name: 'Android Authority',
    googleMode: 'search',
    googleQuery: 'site:androidauthority.com',
    language: 'en',
    topics: ['tech', 'software'],
    weight: 0.8,
  },
  {
    id: 'macrumors',
    name: 'MacRumors',
    googleMode: 'search',
    googleQuery: 'site:macrumors.com',
    language: 'en',
    topics: ['tech', 'software'],
    weight: 0.79,
  },
  {
    id: 'ifixit',
    name: 'iFixit News',
    googleMode: 'search',
    googleQuery: 'site:ifixit.com',
    language: 'en',
    topics: ['tech', 'hardware'],
    weight: 0.78,
  },
  {
    id: 'tomshardware',
    name: "Tom's Hardware",
    googleMode: 'search',
    googleQuery: 'site:tomshardware.com',
    language: 'en',
    topics: ['hardware', 'tech'],
    weight: 0.76,
  },
  {
    id: 'computerbase',
    name: 'ComputerBase',
    googleMode: 'search',
    googleQuery: 'site:computerbase.de',
    language: 'de',
    topics: ['hardware', 'tech', 'reviews'],
    weight: 0.76,
  },
  {
    id: 'reuters',
    name: 'Reuters',
    googleMode: 'search',
    googleQuery: 'site:reuters.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.74,
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg',
    googleMode: 'search',
    googleQuery: 'site:bloomberg.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.74,
  },
  {
    id: 'wsj',
    name: 'Wall Street Journal',
    googleMode: 'search',
    googleQuery: 'site:wsj.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.73,
  },
  {
    id: 'ft',
    name: 'Financial Times',
    googleMode: 'search',
    googleQuery: 'site:ft.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.73,
  },
  {
    id: 'axios',
    name: 'Axios',
    googleMode: 'search',
    googleQuery: 'site:axios.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.72,
  },
  {
    id: 'cnbc',
    name: 'CNBC',
    googleMode: 'search',
    googleQuery: 'site:cnbc.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.71,
  },
  {
    id: 'forbes',
    name: 'Forbes',
    googleMode: 'search',
    googleQuery: 'site:forbes.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.7,
  },
  {
    id: 'fortune',
    name: 'Fortune',
    googleMode: 'search',
    googleQuery: 'site:fortune.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.69,
  },
  {
    id: 'businessinsider',
    name: 'Business Insider',
    googleMode: 'search',
    googleQuery: 'site:businessinsider.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.68,
  },
  {
    id: 'semafor',
    name: 'Semafor',
    googleMode: 'search',
    googleQuery: 'site:semafor.com',
    language: 'en',
    topics: ['tech', 'business'],
    weight: 0.67,
  },
  {
    id: 'nikkeiasia',
    name: 'Nikkei Asia',
    googleMode: 'search',
    googleQuery: 'site:asia.nikkei.com',
    language: 'en',
    topics: ['business', 'tech'],
    weight: 0.66,
  },
  {
    id: 'scmp',
    name: 'South China Morning Post',
    googleMode: 'search',
    googleQuery: 'site:scmp.com',
    language: 'en',
    topics: ['business', 'tech'],
    weight: 0.65,
  },
  {
    id: 'nytimes',
    name: 'New York Times',
    googleMode: 'search',
    googleQuery: 'site:nytimes.com',
    language: 'en',
    topics: ['tech', 'business', 'culture'],
    weight: 0.64,
  },
  {
    id: 'washingtonpost',
    name: 'Washington Post',
    googleMode: 'search',
    googleQuery: 'site:washingtonpost.com',
    language: 'en',
    topics: ['tech', 'policy'],
    weight: 0.63,
  },
  {
    id: 'politico',
    name: 'Politico',
    googleMode: 'search',
    googleQuery: 'site:politico.com',
    language: 'en',
    topics: ['policy', 'tech'],
    weight: 0.62,
  },
  {
    id: 'ap',
    name: 'Associated Press',
    googleMode: 'search',
    googleQuery: 'site:apnews.com',
    language: 'en',
    topics: ['tech', 'general'],
    weight: 0.61,
  },
  {
    id: 'bbc',
    name: 'BBC',
    googleMode: 'search',
    googleQuery: 'site:bbc.com',
    language: 'en',
    topics: ['tech', 'general'],
    weight: 0.6,
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    googleMode: 'search',
    googleQuery: 'site:theguardian.com',
    language: 'en',
    topics: ['tech', 'general'],
    weight: 0.6,
  },
  {
    id: 'npr',
    name: 'NPR',
    googleMode: 'search',
    googleQuery: 'site:npr.org',
    language: 'en',
    topics: ['tech', 'general'],
    weight: 0.59,
  },
  {
    id: 'nbcnews',
    name: 'NBC News',
    googleMode: 'search',
    googleQuery: 'site:nbcnews.com',
    language: 'en',
    topics: ['tech', 'general'],
    weight: 0.58,
  },
  {
    id: 'nbclosangeles',
    name: 'NBC Los Angeles',
    googleMode: 'search',
    googleQuery: 'site:nbclosangeles.com',
    language: 'en',
    topics: ['tech', 'general'],
    weight: 0.58,
  },
  {
    id: 'foxbusiness',
    name: 'Fox Business',
    googleMode: 'search',
    googleQuery: 'site:foxbusiness.com',
    language: 'en',
    topics: ['business', 'tech'],
    weight: 0.57,
  },
  {
    id: 'bloomberglaw',
    name: 'Bloomberg Law',
    googleMode: 'search',
    googleQuery: 'site:bloomberglaw.com',
    language: 'en',
    topics: ['law', 'policy'],
    weight: 0.56,
  },
  {
    id: 'atlantic',
    name: 'The Atlantic',
    googleMode: 'search',
    googleQuery: 'site:theatlantic.com',
    language: 'en',
    topics: ['culture', 'policy'],
    weight: 0.55,
  },
  {
    id: 'variety',
    name: 'Variety',
    googleMode: 'search',
    googleQuery: 'site:variety.com',
    language: 'en',
    topics: ['media', 'business'],
    weight: 0.55,
  },
  {
    id: 'pew',
    name: 'Pew Research Center',
    googleMode: 'search',
    googleQuery: 'site:pewresearch.org',
    language: 'en',
    topics: ['research', 'policy'],
    weight: 0.54,
  },
  {
    id: 'propublica',
    name: 'ProPublica',
    googleMode: 'search',
    googleQuery: 'site:propublica.org',
    language: 'en',
    topics: ['investigations', 'policy'],
    weight: 0.53,
  },
  {
    id: 'nature',
    name: 'Nature',
    googleMode: 'search',
    googleQuery: 'site:nature.com',
    language: 'en',
    topics: ['science', 'research'],
    weight: 0.52,
  },
  {
    id: 'sourcesnews',
    name: 'Sources.news',
    googleMode: 'search',
    googleQuery: 'site:sources.news',
    language: 'en',
    topics: ['general'],
    weight: 0.4,
  },
  {
    id: 'crazystupidtech',
    name: 'Crazy Stupid Tech',
    googleMode: 'search',
    googleQuery: 'site:crazystupidtech.com',
    language: 'en',
    topics: ['general'],
    weight: 0.35,
  },
]
